name = "vaultplay-draw-worker"
main = "src/index.js"
compatibility_date = "2025-10-05"

# Development environment (uses free workers.dev subdomain)
[env.development]
name = "vaultplay-draw-worker"
# This will be available at: https://vaultplay-draw-worker.ops-13d.workers.dev

# Production environment (uses your custom domain)
[env.production]
name = "vaultplay-draw-worker"

# Limits configuration
[limits]
cpu_ms = 50  # Maximum CPU time per request (50ms)
